### PR TITLE
WIP: Update this app's dependencies

### PR DESCRIPTION
**Pull request by jdennes**
:warning: Not ready to merge :warning:

This will be deployed and tested gradually as different dependencies are updated.

### CODE REVIEW

**Comment by jdennes** [comment]
This is more broken than I thought. The names of the POST variables coming through are different than before:

```
{"name"=>"test", "amp;email"=>"test@gmail.com", "amp;note"=>"Remote Volunteer Application: \r\n\nName: test\r\n\nEmail: thisismyemailaddress@gmail.com\r\n\nAddress:\ntest\r\n\nAge: 20\r\n\nAre you a skateboarder? Yes\r\n\nWhy are you interested in the Skateistan project?\ntest\r\n\nHow could you help Skateistan from your current location?\n\r\n\nHow many hours a week could you to dedicate to a remote volunteer position?\n\r\n\nHow many months could you potentially dedicate to a remote volunteer position?\n\n"}
```

For example: `"amp;email"=>"test@gmail.com"`

/cc @manue1 This could be something broken in the website webhook module/setup. Can we double-check that we're sending through the names of the POST values correctly, and that they're not being HTML encoded somehow?

**Comment by manue1** [comment]
I actually made some changes early last year, after the switch to Drupal 7. We wanted to make the emails more readable because the paragraphs are all squeezed together. Then when I tried to add extra line breaks they got stripped. In Drupal 7 even if you try to send an HTML mail it converts it to plain text, so I have to create our own MailSystemInterface which I then never got around to do. But I didn't realize the variables are invalid.

**Comment by jdennes** [comment]
Yeah, it looks like we don't subscribers in our list in Campaign Monitor after 25 Sep 2014. I'm going to do a hack to fix this temporarily, because I want to merge this. Would be good to figure out why those POST variables are coming through like that though.

**Comment by jdennes** [comment]
Yeah, so this works now, by mapping the params has like this in https://github.com/skateistan/skateistanappreceiver/commit/427d460d995fb09cb8a1b3ac98a51bcd884fde37:

```ruby
Hash[params.map { |k, v| [k.gsub("amp;", ""), v] }]
```

:worried:

**Comment by jdennes** [comment]
Everything working. This is getting merged. We can figure out the webhook stuff :soon:.

**Pull request merged**
